export const CategoryList = [
    { value: 1, label: "Teas" },
    { value: 2, label: "Biscuits" },
    { value: 3, label: "Oil" },
    { value: 4, label: "Drinks" },
    { value: 5, label: "Cigarettes" },
    { value: 6, label: "Loundry" },
    { value: 7, label: "Freezer" },
    { value: 8, label: "Groceries" },
    { value: 9, label: "Fish" },
    { value: 10, label: "Lolies" },
    { value: 11, label: "Vegetables" },
    { value: 12, label: "Rice" },
    { value: 13, label: "Poultry" },
    { value: 14, label: "Livestock - Ducks" },
    { value: 15, label: "Livestock - Goats" },
    { value: 16, label: "Livestock - Sheep" },
    { value: 17, label: "Livestock - Cows" },
    { value: 18, label: "Meats" },
    { value: 19, label: "Fresh Fruits" },
    { value: 20, label: "Kitchen Ware" },
    { value: 21, label: "Kitchen" },
    { value: 22, label: "Raw" },
    { value: 23, label: "Animal Feed" },

    { value: 24, label: "Stationery" },
    { value: 25, label: "Cosmetics" },
    { value: 26, label: "Hardware" },
    { value: 27, label: "Apparel" },
    { value: 28, label: "Furniture" },
    { value: 29, label: "Household Essentials" },
    { value: 30, label: "Toys & Games" },
    { value: 31, label: "Footware" },
    { value: 32, label: "Flex" },
    { value: 33, label: "Shoe" },
    { value: 34, label: "Sporting Goods" },
    { value: 35, label: "Electric & Electronics" },
    { value: 36, label: "Mobile Devices" },
    { value: 37, label: "Ornaments" },
    { value: 38, label: "Fashion Design Supplies" },
    { value: 39, label: "Healthcare" },
]