export const CategoryList = [
    { value: 1, label: "Teas" },
    { value: 2, label: "Biscuits" },
    { value: 3, label: "Oil" },
    { value: 4, label: "Drinks" },
    { value: 5, label: "Cigarettes" },
    { value: 6, label: "Loundry" },
    { value: 7, label: "Freezer" },
    { value: 8, label: "Groceries" },
    { value: 9, label: "Fish" },
    { value: 10, label: "Lolies" },
    { value: 11, label: "Vegetables" },
    { value: 12, label: "Rice" },
    { value: 13, label: "Chick (Live)" },
    { value: 14, label: "Duck (Live)" },
    { value: 15, label: "Goat (Live)" },
    { value: 16, label: "Sheep (Live)" },
    { value: 17, label: "Cow (Live)" },
    { value: 18, label: "Meats" },
    { value: 18, label: "Fruits" },
]